modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="vansqmod"
version="1.0.2"
displayName="Vanilla^2 Mod"

description='''
Supporting mod for Minecraft Vanilla^2
'''

[[mixins]]
config="vansqmod.mixins.json"

[[dependencies.vansqmod]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.vansqmod]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.vansqmod]]
modId="quark"
type="required"
versionRange="[4.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.vansqmod]]
modId="barched"
mandatory=true
# 0.0.12 changed spear(Tiers, ...) to spear(Tier, ...) (binary-incompatible).
versionRange="[0.0.12,)"
ordering="AFTER"
side="BOTH"

[[dependencies.vansqmod]]
modId="curios"
type="required"
versionRange="[9.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies.vansqmod]]
modId="backpacks"
type="required"
versionRange="[0.4,)"
ordering="AFTER"
side="BOTH"

[[dependencies.vansqmod]]
modId="caverns_and_chasms"
type="optional"
versionRange="[1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.vansqmod]]
modId="galosphere"
type="optional"
versionRange="[1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.vansqmod]]
modId="beltborne_lanterns"
type="optional"
versionRange="[1.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.vansqmod]]
modId="effortless"
type="optional"
versionRange="[1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.vansqmod]]
modId="dungeonsdelight"
type="optional"
versionRange="[1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.vansqmod]]
modId="endrem"
type="optional"
versionRange="[1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.vansqmod]]
modId="spyglass_improvements"
type="optional"
versionRange="[1.5,)"
ordering="NONE"
side="CLIENT"

[[dependencies.vansqmod]]
modId="spyglass_astronomy"
type="optional"
versionRange="[1.0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.vansqmod]]
modId="combatnouveau"
type="optional"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.vansqmod]]
modId="peaceless"
type="optional"
versionRange="[1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.vansqmod]]
modId="distanthorizons"
type="optional"
versionRange="[3.0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.vansqmod]]
modId="yungscavebiomes"
type="optional"
versionRange="[1.21.1-NeoForge-3.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.vansqmod]]
modId="born_in_chaos_v1"
type="optional"
versionRange="[1.0,)"
ordering="AFTER"
side="BOTH"
